const benefits = [
  'SIMPLE TOOLS',
  'SIMPLE CLOUD DEPLOYMENT',
  'COMMON SENSE DEFAULTS',
  'LIGHTNING PERFORMANCE BY DEFAULT',
  'GLOBAL DISTROBUTION BY DEFAULT',
  'AUTOMATIC SSL ENCRYPTION',
  'ZERO CONFIG FRAMEWORK SUPPORT',
  'SIMPLE CUSTOM DOMAIN MANAGEMENT',
  'SUPPORT FOR MANY POPULAR INTEGRATIONS',
  'FILE BASED ROUTING',
  'NO NEED TO IMPORT REACT',
];

export default (req, res) => res.json(benefits);
